spring.application.name=AdvJava

spring.datasource.name=AdvJava
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.password=InhAjrNwS72ky0SU
spring.datasource.username=postgres.kjszkdqftvzttmyrsndt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=6543

